<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

add_action( 'genesis_before_loop', 'genesis_do_search_title' );
/**
 * Echo the title with the search term.
 *
 * @since 1.9.0
 */
function genesis_do_search_title() {
	//echo __FILE__; 
	$title = sprintf( '<div class="archive-description"><h1 class="archive-title">%s %s</h1></div>', apply_filters( 'genesis_search_title_text', __( 'Search Results for:', 'genesis' ) ), get_search_query() );
	echo apply_filters( 'genesis_search_title_output', $title ) . "\n";
}

/**
 * Returns the featured image count
 *
 * @param integer offset start offset - to allow for a big image at the start 
 * @return integer number of featured images
 */
function genesis_sb_featured_images( $offset ) {
	$images = 0;
	global $wp_query;
	bw_trace2( $wp_query, "wp_query", false );
	if ( property_exists( $wp_query, "featured_images" ) ) {
		$images = $wp_query->featured_images; 
	}
	//echo "Total: " .  $images . PHP_EOL;
	$images = genesis_sb_full_rows( $images, $offset );
	
	//echo "Images: " . $images . PHP_EOL;
	
	return $images;
}

/**
 * Returns the number of full rows
 * 
 * @param integer $total total number of posts remaining with featured images
 * @param integer $entries_per_row number of items in a rows
 * @param integer $maximum_rows we support
 * @return integer  
 */
function genesis_sb_full_rows( $total, $offset=0, $entries_per_row=4, $maximum_rows=4 ) {
	$rows = intdiv( $total-$offset, $entries_per_row );
	//echo $rows;
	$rows = min( $rows, $maximum_rows );
	return ( $rows * $entries_per_row ) + $offset;
}


/**
 * Implement a tighter loop for archives
 * 
 * Basically we don't want any content except the featured image
 * 
 * BUT 
 * one day we might look at {@link https://github.com/desandro/masonry}
 * 
 */
function genesis_oik_do_loop() {
	$count = 0;
	$images = genesis_sb_featured_images( 1 );
	
	if ( have_posts() ) {
		while ( have_posts() ) {
			the_post();
			//do_action( 'genesis_before_entry' );
			if ( $count == 0 ) {
				genesis_sb_hero();
			} elseif ( $count < $images  ) {
				genesis_sb_images();
			} elseif ( $count == $images ) {
				printf( '<div %s>', genesis_attr( "links" ) );
				genesis_sb_after_images();
      } else {
				genesis_sb_after_images();
			}
			$count++;
		}
		echo '</div>';
		do_action( 'genesis_after_endwhile' );
	} else {
		do_action( 'genesis_loop_else' );
	}
}

/**
 * Display the hero banner
 */
function genesis_sb_hero() {
	//echo "<h1>Hero</h1>";
	//genesis_sb_do_post_content();
	printf( '<section %s>', genesis_attr( 'hero' ) );
		do_action( 'genesis_before_entry' );
		printf( '<article %s>', genesis_attr( 'entry' ) );

			do_action( 'genesis_before_entry_content' );
			printf( '<div %s>', genesis_attr( 'hero' ) );
			genesis_do_post_image();
			echo '</div>';
			
			printf( '<div %s>', genesis_attr( 'entry-content' ) );
			do_action( 'genesis_entry_header' );
			do_action( 'genesis_entry_content' );
			do_action( 'genesis_after_entry_content' );
			do_action( 'genesis_entry_footer' );
			echo '</div>';

		echo '</article>';

		do_action( 'genesis_after_entry' );
	echo '</section>';
}

/**
 * Displays images in blocks of 4
 * With Title and Featured image
 */
function genesis_sb_images() {
	printf( '<article %s>', genesis_attr( 'image' ) );
	//do_action( 'genesis_before_entry_content' );
	//echo '<div class="imgwrap">';
	//echo '</div>';
	printf( '<div %s>', genesis_attr( 'entry-content' ) );
	do_action( 'genesis_entry_header' );
	genesis_do_post_image();
	//do_action( 'genesis_entry_content' );
	echo '</div>';
	//do_action( 'genesis_after_entry_content' );
	//do_action( 'genesis_entry_footer' );
	echo '</article>';
	//do_action( 'genesis_after_entry' );
}

/**
 * Display links from now for the rest of the page
 * 
 * 
 */
function genesis_sb_after_images() {
	//do_action( 'genesis_entry_header' );
	$title =  get_the_title();
	$extra = styled_styles( $title );
	echo retlink( null, get_permalink(), $title, null, null, $extra );
	echo " ";
 // genesis_do_post_title();
}

/**
 * Enqueue special styles for archives
 */
function genesis_sb_after_footer() {
	$timestamp = null;
	if ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) {
		$timestamp = filemtime( get_stylesheet_directory() . "/search.css" );
	}
	wp_enqueue_style( "archive-css", get_stylesheet_directory_uri() . '/search.css', array(), $timestamp );
}
 
 
/*
 * Output from genesistant
 *
 * We don't want either post_content nor post_content_nav
 * but we do want the image and may need the post permalink
 * but this should be before the image
 * 
 * `
 * <!--
 * action genesis_entry_content genesis_loop,genesis_entry_content
 *
 * : 8   genesis_do_post_image;1
 * : 10   genesis_do_post_content;1
 * : 12   genesis_do_post_content_nav;1
 * : 14   genesis_do_post_permalink;1--> 
 */
remove_action( "genesis_entry_content", "genesis_do_post_image", 8 );
remove_action( "genesis_entry_content", "genesis_do_post_content", 10 );
//remove_action( "genesis_entry_content", "genesis_do_post_content_nav", 12 ); 
//remove_action( "genesis_entry_content", "genesis_do_post_permalink", 14 );
//add_action( "genesis_entry_content", "genesis_do_post_permalink", 9 );
 
// Not necessary to remove these hooks if we don't invoke the action
 
//remove_action( "genesis_entry_footer", 'genesis_oik_post_info' );
//remove_action( "genesis_entry_footer", "genesis_entry_footer_markup_open", 5);
//remove_action( "genesis_entry_footer", "genesis_entry_footer_markup_close", 15 );
//remove_action( "genesis_entry_header", "genesis_do_post_format_image", 4 );

remove_action( "genesis_loop", "genesis_do_loop" );
add_action( "genesis_loop", "genesis_oik_do_loop" );


//add_action( "genesis_after_footer", "genesis_oik_after_footer" );
add_action( "wp_enqueue_scripts", "genesis_sb_after_footer" );

// add_action( "genesis_after_endwhile", "genesis_oik_a2z", 9 );

function styled_styles( $sb ) {
	$words = explode( " ", $sb . 'SS BB' );
	$sword = $words[0];
	$sletter = substr( $sword, 0, 1 );
	 
	$sord = ord( $sletter ) ;
	$bword = $words[1];
	$bletter = substr( $bword, 0, 1 );
	$bord = ord( $bletter ) ;
	$blue = 255 - ( 10 * strlen( $sb ) );
	$alpha = "0.9";
	$style = sprintf( ' style="color: rgba( %1$s, %2$s, %3$s, %4$s );"', $sord, $bord, $blue, $alpha );
	return $style;
}

function styled_block( $sb ) {
	$classes = "sb ";
	$html = '<div class="'; 
	$html .= $classes;
	$html .= '"';
	$html .= styled_styles( $sb );
	$html .= '>';
	$html .= $sb;
	$html .= '</div>';
	return $html;
}



function genesis_sb_image_default_args( $defaults, $args ) {
	bw_trace2();
	//$sb = get_the_title();
	$html = styled_block( get_the_title() );
	
	$defaults['fallback'] =  array( "html" => $html, "url" => get_permalink() );
	return $defaults;
}

add_filter( "genesis_get_image_default_args", "genesis_sb_image_default_args", 10, 2 );

genesis();
